[package]
name = "opentelemetry-aws-temporary-fork"
version = "0.1.0"
description = "[TEMPORARY FORK - WILL BE YANKED] ⚠️⚠️⚠️ TEMPORARY FORK OF opentelemetry-aws - INTENDED TO BE DEPRECATED ONCE UPSTREAM PR #549 IS MERGED ⚠️⚠️⚠️ DO NOT USE DIRECTLY"
homepage = "https://github.com/RustyServerless/opentelemetry-rust-contrib/tree/publish-fork/aws-xray-exporter/opentelemetry-aws"
repository = "https://github.com/RustyServerless/opentelemetry-rust-contrib/tree/publish-fork/aws-xray-exporter/opentelemetry-aws"
readme = "README.md"
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
]
keywords = ["opentelemetry", "tracing"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.75.0"

[lib]
name = "opentelemetry_aws"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["trace", "internal-logs", "xray-exporter"]
internal-logs = ["dep:tracing"]

trace = ["opentelemetry/trace", "opentelemetry_sdk/trace"]
detector-aws-lambda = ["dep:opentelemetry-semantic-conventions"]

xray-exporter = [
    "opentelemetry/trace",
    "opentelemetry_sdk/trace",
    "dep:opentelemetry-semantic-conventions",
    "dep:serde_json",
    "dep:thiserror",
    "dep:regex",
    "dep:url",
    "dep:rand"
]
xray-daemon-client = ["xray-exporter"]
xray-stdout-client = ["xray-exporter"]
subsegment-nesting = []

[dependencies]
opentelemetry = "0.31"
opentelemetry_sdk = { version = "0.31", default-features = false, optional = true }
opentelemetry-semantic-conventions = { version = "0.31", optional = true, features = [
    "semconv_experimental",
] }
tracing = {version = "0.1", optional = true}
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0", optional = true}
thiserror = {version = "1.0", optional = true}
regex = {version = "1.0", optional = true}
url = {version = "2.0", optional = true}
rand = {version = "0.9", optional = true}

[dev-dependencies]
opentelemetry-aws-temporary-fork = {path = ".", features = ["subsegment-nesting", "xray-daemon-client"] }
opentelemetry_sdk = { version = "0.31", default-features = false, features = ["testing"] }
opentelemetry-http = "0.31"
opentelemetry-stdout = { version = "0.31", default-features = false, features = ["trace"] }
hyper = { version = "1.4.1" }
tokio = { version = "1.0", features = ["macros", "rt"] }
sealed_test = "1.1"
temp-env = "0.3"
criterion = { version = "0.7", features = ["html_reports", "async_tokio"] }
pprof = { version = "0.14.1", features = ["flamegraph", "criterion"]}
rand = "0.9"

[[bench]]
name = "xray_exporter"
harness = false

[package.metadata.cargo-machete]
ignored = ["tracing"]

[lints.rust]
rust_2024_compatibility = { level = "warn", priority = -1 }
if_let_rescope = "allow"
tail_expr_drop_order = "allow"

[lints.clippy]
all = { level = "warn", priority = 1 }
